[package]
name = "redog-adapter"
version.workspace = true
edition.workspace = true

[dependencies]
redog-core = { workspace = true }
redog-common = { workspace = true }
redog-transport = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
